
default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: survey
  
test:
  <<: *default
  database: survey_test